#pragma once

using namespace ATL;

template <class T>
class CProxy_ILoopbackDeviceEvents : public IConnectionPointImpl<T, &__uuidof( _ILoopbackDeviceEvents ), CComDynamicUnkArray>
{
	// WARNING: This class may be regenerated by the wizard
public:
};
